In [2]:
import numpy as np

In [3]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
a=np.array([1,2,3])
#universal functions 

print(np.exp(a))
print(np.sqrt(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log2(a))
print(np.log10(a))

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]


In [6]:
#array slicing and indexing 
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
b[1]

array([5, 6, 7, 8])

In [11]:
b[1:]
# until the end

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
b[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [13]:
b[0:2,2:]

array([[3, 4],
       [7, 8]])

In [15]:
###statistic concepts  normalization
##if a man has mean 0 and standard deviation 1, then he is normal distribution 
data=np.array([1,2,3,4,5])
mean=data.mean()
std=data.std()
normalized=(data-mean)/std
normalized


array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [17]:
#logical operations 
data=np.array([1,2,3,4,5])
data[data>3]

array([4, 5])